---
language: python

python: 3.7

env:
  global:
    - DOCKER_CACHE=$HOME/docker
    - WEB_CACHE=$DOCKER_CACHE/service_web:latest

cache:
  bundler: true
  directories:
    - $DOCKER_CACHE

jobs:
  include:
    - stage: test
      services: docker
      install:
        - cd service
        - docker-compose build web
        - docker-compose up -d web
        - docker ps -a
      script: docker-compose exec web /code/manage.py test --keepdb pages
      after_sucess:
        - docker-compose stop web
        - docker ps -a
    - stage: build
      name: web
      services: docker
      script: docker build -t service_web:latest service/web
    - stage: build
      name: web (with cache)
      services: docker
      before_install: >
        if [[ -f $WEB_CACHE ]]; then zcat $WEB_CACHE | docker load; fi
      script: >
        docker build -t service_web:latest --cache-from service_web:latest service/web
      before_cache: >
        mkdir -p $HOME/docker &&
        docker save service_web:latest | gzip -2 > "$WEB_CACHE"
    - stage: build
      name: nginx
      services: docker
      script: docker build -t service_nginx:latest service/nginx
