language: python
python: 3.7
jobs:
  include:
   - stage: test
     services: docker
     before_install:
       - docker build -t service_web:latest service/web
       - pwd && ls
       - docker-compose up -d web
       - docker ps -a
     script: docker exec /code/manage.py test --keepdb pages
     after_sucess:
       - docker stop service_web_1
       - docker ps -a
   - stage: build
     services: docker
     script:
       - docker build -t service_web:latest service/web
       - docker build -t service_nginx:latest service/nginx

