---
language: python

python: 3.7

cache:
  bundler: true
  directories:
    - $HOME/docker

jobs:
  include:
    - stage: test
      services: docker
      install:
        - cd service
        - docker-compose build web
        - docker-compose up -d web
        - docker ps -a
      script: docker-compose exec web /code/manage.py test --keepdb pages
      after_sucess:
        - docker-compose stop web
        - docker ps -a
    - stage: build
      name: web
      services: docker
      script: docker build -t service_web:latest service/web
    - stage: build
      name: web (with cache)
      services: docker
      before_install: >
        if [[ -d $HOME/docker ]]; then zcat $HOME/docker/service_web:latest.tar.gz | docker load; fi
      script: >
        docker build -t service_web:latest --cache-from service_web:latest service/web
      before_cache: >
        mkdir -p $HOME/docker &&
        docker save service_web:latest | gzip -2 > "$HOME/docker/service_web:latest.tar.gz"
    - stage: build
      name: nginx
      services: docker
      script: docker build -t service_nginx:latest service/nginx
