language: python
python: 3.7
jobs:
  include:
   - stage: test
     install: pip3 install -r service/web/requirements.txt
     script: python3 service/web/manage.py test
   - stage: build
     services: docker
     script:
       - docker build -t service_web:latest service/web
       - docker build -t service_nginx:latest service/nginx

