language: python
python: 3.7
jobs:
  include:
   - stage: test
     services: docker
     install:
       - cd service
       - docker-compose build web
       - docker-compose up -d web
       - docker ps -a
     script: docker-compose exec web /code/manage.py test --keepdb pages
     after_sucess:
       - docker-compose stop web
       - docker ps -a
   - stage: build
     services: docker
     script: docker build -t service_web:latest service/web
     script: docker build -t service_nginx:latest service/nginx
 
