version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Build testing image
          docker:
            - image: docker:stable
          command: |
            cd service
            docker-compose build web
            docker-compose up -d web
            docker-compose exec web python /code/manage.py pages

workflows:
  version: 2
  test:
    jobs:
      - test

