version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build testing image
          command: |
            cd service
            docker-compose build web
            docker-compose up -d web
            docker-compose exec web python /code/helloworld/manage.py pages

workflows:
  version: 2
  test:
    jobs:
      - test

