version: '3.2'

services:
  nginx:
    build: nginx/
    command: nginx -g 'daemon off;'
    ports:
      - 80:80

  web:
    build: web/
#    command: sleep 6000
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/helloworld:/code
    ports:
      - 8000:8000
